services:
    cache:
        class:     'Opine\Cache'
    topic:
        class:     'Opine\PubSub\Topic'
        arguments: ['@container']
    config:
        class:     'Opine\Config'
        arguments: ['%root%', '@cache']
    db:
        class:     'Opine\Mongo'
        arguments: ['@config', '@topic']
    yamlSlow:
        class:     'Symfony\Component\Yaml\Yaml
